<p style="margin: 0px 0px 10px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;"><strong>Effective Date: January 01, 2017&nbsp;</strong></span></p>
<p style="margin: 0px 0px 10px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">IMPORTANT: Please read this Privacy Policy carefully to understand our policies and practices regarding your information and how we will treat it. If you do not agree with our policies and practices, your choice is not to use the Service (as defined below). By accessing or using our Service, you agree to this Privacy Policy. Please note that Your use of the Service constitutes Your acceptance of this Policy as set forth below. This Policy may change from time to time. Your continued use of the Service after We make changes constitutes Your acceptance of those changes, so please check the Policy periodically for updates.</span></p>
<p style="margin: 0px 0px 10px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;"><strong>1. Introduction</strong></span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">1.1 MagnoAPPS WLL (hereinafter referred to as &ldquo;MagnoAPPS&rdquo;, the &ldquo;Company,&rdquo; &ldquo;We,&rdquo; &ldquo;Ourselves&rdquo;, &ldquo;Us,&rdquo; or &ldquo;Our&rdquo;) is committed to maintaining robust privacy protections for its users and visitors. This Privacy Policy (&ldquo;Privacy Policy&rdquo; or &ldquo;Policy&rdquo;) is designed to help you understand how we collect, use, disclose, and safeguard the information you provide to us and to assist you in making informed decisions when using our Service.&nbsp;</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">1.2 For purposes of this Agreement, the following terminology applies:&nbsp;</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;"> &mdash; The Company&rsquo;s Service which can be accessed through any of Our affiliated mobile device applications (&ldquo;App&rdquo;) and/or through Our Website (&ldquo;Website&rdquo;) at <a href="http://www.Eclat.co"><span style="font-size: 10px; line-height: normal; -webkit-font-kerning: none;">www.Eclat.co</span></a>, is hereinafter collectively referred to as the &ldquo;Service&rdquo; or &ldquo;Eclat&rdquo;;</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;"> &mdash;"User", &ldquo;You&rdquo; and &ldquo;Your&rdquo; refers to You, the person accessing and/or Using the Service.</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;"> Any Use of the above terminology or other words in the singular, plural, capitalizations and/or he/she or they, are taken as interchangeable and therefore as referring to same.&nbsp;</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">1.3 Please note that certain features or services referenced in this Privacy Policy may not be offered on the Service at all times. Please also review our Terms of Service, which governs your use of the Service, and which is accessible at&nbsp;http://www.Eclat.co/Terms</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">1.4 By accessing or using the Service, you consent to the information collection, disclosure and use practices described in this Privacy Policy.</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">1.5 Our Policy applies to&nbsp;all visitors, Users, and others who access or use the Service. &nbsp;</span></p>
<p style="margin: 0px 0px 10px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;"><strong>2. Contact Us</strong></span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">2.1 Should you have any questions or concerns regarding this Privacy Policy, please contact us at support@Eclat.co</span></p>
<p style="margin: 0px 0px 10px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;"><strong>3. Collecting information</strong></span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">3.1 We may collect, store and use the following kinds of personal information:&nbsp;</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(a) Information about your device and about your visits to and use of this Service including your IP address, geographical location, device and platform type and version, operating system, referral source, length of visit, preferences you submit and preferences that are generated based on the data you submit, views and Service navigation paths;</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(b) Information that you provide to us when registering with our Service including your email, name, password, profile picture, date of birth;</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(c) Profile information that you provide for your user profile including your email, name, phone number, profile picture, gender, date of birth, interests and hobbies, educational and employment information;</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(d) Information that you provide to us for the purpose of subscribing to our email notifications and/or newsletters including your name and email address;</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(e) Information that you provide to us when using the Service, or that is generated in the course of the use of the Service including the timing, frequency and pattern of Service use;</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(f) Information that you post to our Service for publication on our Service and/or the internet including your user name, your profile picture and the content of your posts;</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(g) Information contained in or relating to any communication that you send to us or send through our Service including the communication content and metadata associated with the communication;</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(h) Additional information such as physical address and additional authentication information, to provide you with the services you need (such as the ability to view nearby posts based on location proximity), or to ensure the integrity of our Service (for example, prevention of fraud). We collect information to provide better services and enhanced user experience to all of Our Users.</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(i) Any other personal information that you choose to send to us.</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">3.2 Location information:&nbsp;</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(a) When you use our Service, and with your permission, we collect and process information about your precise location. This information is used to match service offers and requests for which location and location proximity is relevant.</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(b) We may also collect the precise location of your device when the app is running in the foreground or background.</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(c) We may also derive your approximate location from your IP address.</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">3.3 We may also receive information from other sources and combine that with information We collect through Our Service. For example: If you choose to link, create, or log in to your account with a social media service (e.g., Facebook), we may receive information about you or your connections from that site or app.</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">3.4 Additional authentication information:&nbsp;</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(a) When you use Our Service, and with your permission, we may ask you to enter your phone number before you are able to upload, publish, advertise or display (hereinafter, &ldquo;post&rdquo;) content or material on the Service. To verify your phone number before posting, you must follow the steps provided on the Service when prompted to do so. This authentication is required to ensure the integrity of our Service is maintained and to prevent fraud, spam and/or fake or misleading user accounts and posts or content.</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(b) Your phone number and other contact details (such as your email address) will remain hidden and cannot be viewed by other Service Users. Your contact details (including your phone number) will be made publicly visible to other Users only if and when You expressly enable such feature on the App or Service where applicable. If you decide to make visible to other users the foregoing, other users will be able to and may contact You via such enabled contact details.</span></p>
<p style="margin: 0px 0px 10px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;"><strong>4. Using information</strong></span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">4.1 Personal information submitted to us through our Service will be used for the purposes specified in this Policy or on the relevant pages of the Service.</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">4.2 We may use Your personal information to:&nbsp;</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(a) administer Our Service, Website, and any of Our affiliated mobile device Apps;</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(b) personalize and improve Our Service, Website, and any of Our affiliated mobile Apps for You;</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(c) enable Your use of the Service;</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(d) respond to any questions or queries that You send to Us;</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(e) deal with enquiries and complaints made by or about You relating to Our Service;</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(f) provide the features and functionality of Our Service to You;</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(g) send You electronic newsletters or promotional e-mails, for which You can opt out at any time if You no longer require to receive such communications;</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(h) keep Our Website secure and prevent fraud;</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(i) verify compliance with our Terms of Service governing the use of Our Service, including monitoring private messages sent through Our Service; and</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(j) send You marketing communications relating to Our business or the businesses of carefully-selected third parties which we think may be of interest to You, by post or, where You have specifically agreed to this, by email or similar technology. You can inform us at any time if You no longer require marketing communications;</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">4.3 If you submit personal information for publication on Our Service, Website, or any of our affiliated mobile device Apps, We will publish and otherwise use that information in accordance with the license You grant to Us.</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">4.4 We may use records of chat sessions for support, training, improvements, and to otherwise enforce the Terms of Service Agreement.&nbsp;</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">4.5 If you provide feedback to Us, We may use and disclose such feedback for any purpose, provided We do not associate such feedback with Your personal information, unless You express Your consent to otherwise display Your personal information.</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">4.6 We will not, without Your express consent, supply Your personal information to any third party for the purpose of their or any other third party's direct marketing.</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">4.7 We may create anonymous information records from personal information by excluding information that would otherwise make the anonymous information personally identifiable to You. This information is aggregated and used in statistical analysis to help us analyze patterns in the use of Our Service. This Privacy Policy does not limit Our use or disclosure of any anonymous information in any way, and We reserve the right to use and disclose anonymous information to third parties at Our discretion.</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">4.8 In addition, you understand that use of Our Service may include the disclosure and display of Your location, location proximity, and/or distance data in relation to other users.</span></p>
<p style="margin: 0px 0px 10px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;"><strong>5. Disclosing personal information</strong></span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">5.1 We may disclose Your personal information to any of Our employees, officers, insurers, professional advisers, agents, suppliers or subcontractors insofar as reasonably necessary for the purposes set out in this Policy.</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">5.2 Although We currently do not have a parent or holding company, any subsidiaries, joint ventures, or other companies under a common control, we may in the future, and We may disclose some or all of Your personal information with these companies insofar as reasonably necessary for the purposes set out in this Policy.</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">5.3 When a user posts an offer to perform a service or a request for a service to be performed within the Service, all other users will be able to view the full content of that post, including any images, location information, contact details and any other information which the user may have chosen to include at the time of submitting the post.</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">5.4 We may disclose your personal information:&nbsp;</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(a) to the extent that We are required to do so by law;</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(b) in connection with any ongoing or prospective legal proceedings;</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(c) in order to establish, exercise or defend Our legal rights including providing information to others for the purposes of fraud prevention and reducing credit risk;</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(d) to the purchaser or prospective purchaser of any business or asset that We are or are contemplating selling; and</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(e) to any person who We reasonably believe may apply to a court or other competent authority for disclosure of that personal information where, in Our reasonable opinion, such court or authority would be reasonably likely to order disclosure of that personal information.</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(f) to Our affiliates for use as described in this Policy.</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">5.5 We may disclose non-personally identifiable information to third-party partners in furtherance of Our business arrangements with them, including without limitation to jointly offer a product or service to You or create interoperability between Our products and services and the products and services of such partners.</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">5.6 In the event the Company goes through a business transition such as a merger, acquisition by another company, or sale of all or a portion of its capital stock or assets, reorganization, consolidation or similar transaction, your Personal Information may be among the assets transferred. You acknowledge that such transfers may occur and are permitted by this Privacy Policy, and that any acquirer of the Company or its assets may continue to process Your Personal Information as set forth in this Privacy Policy.</span></p>
<p style="margin: 0px 0px 10px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;"><strong>6. International data transfers</strong></span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">6.1 Information that we collect may be stored and processed in and transferred between any of the countries in which our servers are located and/or we operate in order to enable us to use the information in accordance with this Policy.</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">6.2 Information that we collect may be transferred to the following countries which do not have data protection laws equivalent to those in force in the European Economic Area: the United States of America, Russia, Japan, China and India.</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">6.3 Personal information that you publish on Our Service</span> <span style="font-kerning: none;">or submit for publication on or in relation to Our Service or Website may be available, via the internet, around the world. We cannot prevent the use or misuse of such information by others.</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">6.4 You expressly agree to the transfers of personal information described in this Section 6.</span></p>
<p style="margin: 0px 0px 10px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;"><strong>7. Retaining personal information</strong></span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">7.1 This Section 7 sets out our data retention policies and procedure, which are designed to help ensure that we comply with our legal obligations in relation to the retention and deletion of personal information.</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">7.2 You can log into your account and view and amend your account information at any time. Please note that while changes to your profile information are reflected promptly in active user databases, our servers may retain previously provided information. If you wish to delete Your account, please contact us on <a href="mailto:support@Eclat.co"><span style="font-size: 10px; line-height: normal; -webkit-font-kerning: none;">support@Eclat.co</span></a>. Please note that deleting the App from Your device will not terminate Your account. Additionally, deletion of your user account will not result in the deletion of usage data related to Your account.&nbsp;</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">7.3 Notwithstanding the other provisions of this Section 7, we will retain documents and information containing personal data:&nbsp;</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(a) to the extent that we are required to do so by law;</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(b) if we believe that the documents may be relevant to any ongoing or prospective legal proceedings; and</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(c) in order to establish, exercise or defend our legal rights (including providing information to others for the purposes of fraud prevention and reducing credit risk).</span></p>
<p style="margin: 0px 0px 10px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;"><strong>8. Security of information we collect</strong></span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">8.1 We will take reasonable technical and organizational precautions to prevent the loss, misuse or alteration of Your personal information.&nbsp;</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">8.2 The information (personally and non-personally identifiable information) we collect about you is stored in limited access servers. We will maintain reasonable safeguards to protect the security of these servers and the information collected through Our Service. However, You understand and acknowledge that no security measures are 100% effective, and no company, including MagnoAPPS WLL, can fully eliminate security risks connected to handling information on the internet. As such, You acknowledge and agree that We cannot guarantee the security of Your personally identifiable information. We expressly disclaim any representation or warranty, whether express or implied, with respect to ensuring, guaranteeing or otherwise offering any definitive promise of security in connection with Your personal (and/or non-personally identifiable) information or usage information.&nbsp;</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">8.3 You acknowledge that the transmission of information over the internet is inherently insecure, and we cannot guarantee the security of data sent over the internet.</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">8.4 The Company does not recommend using the Service to exchange any financial, medical or other sensitive information (including credit card details).</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">8.5 You are responsible for keeping the password You use for accessing Our Service confidential; we will not ask You for Your password (except when You log in to the Service).</span></p>
<p style="margin: 0px 0px 10px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;"><strong>9. Amendments</strong></span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">9.1 We may revise this Privacy Policy from time to time.</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">9.2 You should check this space regularly to ensure You are aware and happy with any changes to the Privacy Policy. The amended Privacy Policy takes effect from the date of publication of the amended Privacy Policy on this space, and You hereby waive any right You may otherwise have to be notified of, or to consent to, revisions of this Privacy Policy. You agree that You are responsible for regularly checking this space for any updates, amendments, or changes in relation to the Privacy Policy.</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">9.3 You further agree that any further use that You make in connection with the Service after the effective date of the amended Privacy Policy will constitute Your binding acceptance to any such amended Policy. If You do not agree to be bound by the revised Privacy Policy, You must stop using the Service.&nbsp;</span></p>
<p style="margin: 0px 0px 10px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;"><strong>10. Analytics</strong></span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">10.1 We use a tool called &ldquo;Google Analytics&rdquo; to collect information about use of Our Service and Website. Google Analytics is a web analytics tool that helps Us understand how users and/or visitors engage with our Website and/or Service. Google Analytics collects information such as how often users visit Our Website and/or Service, what pages or sections they visit when they do so, or the demographic distribution of visitors and/or users of Our Website and Service. Additionally, information about your computer, including your IP address, operating system and browser type, may be collected in order to produce aggregate insights and create reports and/or statistical data without identifying individual visitors or users. Such reports and statistical data helps in identifying possible ways of improving our Website and Service for Our users. For information about the privacy practices of Google Analytics, you can visit <a href="https://www.google.com/policies/privacy/"><span style="font-size: 10px; line-height: normal; -webkit-font-kerning: none;">https://www.google.com/policies/privacy/</span></a> and <a href="http://www.google.com/policies/privacy/partners/"><span style="font-size: 10px; line-height: normal; -webkit-font-kerning: none;">http://www.google.com/policies/privacy/partners/</span></a>. If you elect to opt-out of data collection by Google Analytics (to the extent available) and subsequently use the Service through a different device or otherwise change your cookie or privacy settings on your device, you will need to opt-out again.</span></p>
<p style="margin: 0px 0px 10px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;"><strong>11. Your rights</strong></span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">11.1 The Company will comply with individual&rsquo;s requests regarding access, correction, and/or deletion of the personal data it stores in accordance with applicable law.&nbsp;</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">11.2 We may withhold personal information that You request to the extent permitted by law.</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">11.3 You may instruct us at any time not to process Your personal information for marketing purposes.</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">11.4 You may opt out of receiving promotional messages from Us by following the instructions in those messages. If you opt out, We may still send You non-promotional communications, such as those about Your account, about services you have requested, or Our ongoing business relations.</span></p>
<p style="margin: 0px 0px 10px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;"><strong>12. Third parties</strong></span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">12.1 Our Service may include hyperlinks to, and details of, third party Websites.</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">12.2 We have no control over, and are not responsible for, the privacy policies and practices of third parties.</span></p>
<p style="margin: 0px 0px 10px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;"><strong>13. Updating information</strong></span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">13.1 Please let us know if the personal information that we hold about you needs to be corrected or updated.</span></p>
<p style="margin: 0px 0px 10px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;"><strong>14. Our details</strong></span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">14.1 This Service (including the Website and affiliated mobile Apps) is owned and operated by <em>MagnoAPPS WLL</em></span><span style="font-size: 10px; line-height: normal; font-family: Helvetica; -webkit-font-kerning: none;">.</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-size: 10px; line-height: normal; font-family: Helvetica; -webkit-font-kerning: none;">14</span><span style="font-kerning: none;">.2 We are registered in the Kingdom of Bahrain, and Our principal place of business is in the Kingdom of Bahrain</span></p>
<p style="margin: 0px 0px 10px 30px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-size: 10px; line-height: normal; font-family: Helvetica; -webkit-font-kerning: none;">14</span><span style="font-kerning: none;">.3 You can contact Us:</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(a) by post, using the postal address [MagnoAPPS WLL, PO BOX 17241, Manama, Kingdom of Bahrain];</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(b) Using Our Website contact form;</span></p>
<p style="margin: 0px 0px 10px 60px; text-indent: -30px; font-weight: normal; font-size: 10px; line-height: normal; font-family: Verdana; -webkit-text-stroke-width: initial; -webkit-text-stroke-color: #000000;"><span style="font-kerning: none;">(c) by email, on support@Eclat.co.</span></p>